services:
  - type: web
    name: focototal-backend
    env: node
    region: ohio
    plan: free
    rootDir: back-end
    buildCommand: npm run render:build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: focototal-db
          property: connectionString
      - key: NODE_OPTIONS
        value: "--no-deprecation"

databases:
  - name: focototal-db
    databaseName: focototal
    user: focototal
